server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.2.126
  data:
    mongodb:
#      uri: mongodb://192.168.2.126:27017/leyou
      uri: mongodb://39.105.136.112:27017/leyou
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
leyou:
  jwt:
    pubKeyPath:  C:\temp\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称