server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/leyou
    url: jdbc:mysql://39.105.136.112:8066/leyou?characterEncoding=utf-8
  redis:
#    host: 192.168.2.126
    host: 39.105.136.112
  rabbitmq:
    virtual-host: /leyou
#    host: 192.168.2.126
    host: 39.105.136.112
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
