server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
#    host: 192.168.2.126
    host: 39.105.136.112
    username: leyou
    password: leyou
    virtual-host: /leyou

leyou:
  sms:
    accessKeyId: LTAIo7k2bTXllcD6  # 你自己的accessKeyId
    accessKeySecret: XD1xJ5DRXMxI7jOE5HN5Mdt7jUgswo # 你自己的AccessKeySecret
    signName: 乐优 # 签名名称
    verifyCodeTemplate: SMS_172737264 # 模板名称
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10